- name: Give permissions to everyone for analog dance pads
  copy:
    content: |
      SUBSYSTEM=="input", GROUP="input", MODE="0666"
      SUBSYSTEM=="usb", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="204f", MODE:="666", GROUP="plugdev"
      KERNEL=="hidraw*", ATTRS{idVendor}=="03eb", ATTRS{idProduct}=="204f", MODE="0666", GROUP="plugdev"
    dest: /etc/udev/rules.d/98-permissions-to-analog-dance-pads.rules
  register: udev

- name: Reload udev permissions
  shell: udevadm control --reload
  when: udev.changed

- name: Install libusb-dev
  apt:
    package: libusb-dev

- name: Create directory for nvm
  file:
    path: /opt/nvm
    state: directory
    owner: mckyla
    group: mckyla

- name: Install nvm
  shell: curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | NVM_DIR=/opt/nvm bash
  args:
    creates: /opt/nvm/nvm.sh

- name: Install Node.js 12 via nvm
  shell: export NVM_DIR=/opt/nvm && . /opt/nvm/nvm.sh && nvm install v12.22.12
  args:
    creates: /opt/nvm/versions/node/v12.*

- name: Symlink node binary globally
  file:
    src: /opt/nvm/versions/node/v12.22.12/bin/node
    dest: /usr/local/bin/node
    state: link

- name: Symlink npm binary globally
  file:
    src: /opt/nvm/versions/node/v12.22.12/bin/npm
    dest: /usr/local/bin/npm
    state: link

- name: Symlink npx binary globally
  file:
    src: /opt/nvm/versions/node/v12.22.12/bin/npx
    dest: /usr/local/bin/npx
    state: link

- name: Create directory for analog-dance-pad
  file:
    path: /opt/analog-dance-pad
    state: directory
    owner: mckyla
    group: mckyla

- name: Clone source for analog-dance-pad
  git:
    repo: https://github.com/kauhsa/analog-dance-pad
    dest: /opt/analog-dance-pad
    force: yes
  register: source
  become_user: mckyla
  diff: false

- name: Install dependencies
  shell: npm install --no-save || true
  args:
    chdir: /opt/analog-dance-pad/server
  when: source.changed
  become_user: mckyla

- name: Fix Python 3 incompatible file mode in node-gyp
  replace:
    path: /opt/nvm/versions/node/v12.22.12/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py
    regexp: "'rU'"
    replace: "'r'"

- name: Install dependencies again because node-gyp something python 3 something :D
  shell: npm install --no-save
  args:
    chdir: /opt/analog-dance-pad/server
  when: source.changed
  become_user: mckyla

- name: Build server
  shell: npm run build
  args:
    chdir: /opt/analog-dance-pad/server
  when: source.changed
  become_user: mckyla

- name: Create analog-dance-pad service
  copy:
    src: files/analog-dance-pad.service
    dest: /etc/systemd/system/analog-dance-pad.service
  notify: restart analog-dance-pad.service

- name: Enable analog-dance-pad service
  systemd:
    name: analog-dance-pad
    state: started
    daemon_reload: yes
    enabled: yes

- name: Create directory for analog-dance-pad
  file:
    path: /opt/teensy-loader-cli
    state: directory
    owner: mckyla
    group: mckyla

- name: Get teensy loader CLI source
  git:
    repo: https://github.com/PaulStoffregen/teensy_loader_cli
    dest: /opt/teensy-loader-cli
  register: teensy_loader_source
  become_user: mckyla
  diff: false

- name: Build server
  shell: make
  args:
    chdir: /opt/teensy-loader-cli
  when: teensy_loader_source.changed
  become_user: mckyla
