- name: Remove leftover DVD apt source
  file:
    path: /etc/apt/sources.list.d/dvd.list
    state: absent

- name: Install utility packages
  apt:
    package: vim,htop,rsync,git,curl

- name: Enable passwordless sudo for mckyla
  lineinfile:
    path: /etc/sudoers
    line: "mckyla ALL=(ALL) NOPASSWD:ALL"
    regexp: "^mckyla"
    validate: "/usr/sbin/visudo -cf %s"
    insertbefore: "^root "

- name: Disable apt-daily-service.timer
  systemd:
    name: apt-daily-upgrade.timer
    enabled: no
    state: stopped
  tags: [systemd]

- name: Disable apt-daily.timer
  systemd:
    name: apt-daily.timer
    enabled: no
    state: stopped
  tags: [systemd]

- name: Disable automatic system suspend
  copy:
    content: |
      [Sleep]
      AllowSuspend=no
      AllowHibernation=no
      AllowSuspendThenHibernate=no
      AllowHybridSleep=no
    dest: /etc/systemd/sleep.conf
  tags: [systemd]
