- name: Install AMD GPU firmware and Mesa drivers
  apt:
    package: libdrm-amdgpu1,xserver-xorg-video-amdgpu
    update_cache: yes

- name: Make sure X.org configuration directory exists
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: Install Xorg configuration file
  copy:
    src: files/20-amdgpu.conf
    dest: /etc/X11/xorg.conf.d/20-amdgpu.conf
